name: docs

on:
  release:
    branches: [main]
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          # fetch all commits to get last updated time or other git log info
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          # choose node.js version to use
          node-version: '18'

      # install dependencies if the cache did not hit
      - name: Install dependencies
        run: npm ci && npm run docs:install

      # run build script
      - name: Build Documentation site
        run: npm run docs:gen && npm run docs:build && npm run add-domain

      # deploy to gh-pages
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3.9.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/.output/public
